### ISSUE TITLE
Enquire about two Abbreviations

### ISSUE THREAD

**Issue by Deepyman** [FZJ-IEK3-VSA/hplib#30]
Hi! Thanks for this valuable work. May I ask one easy question?
What is the 
**_"Input temperature in °C at primary side of the heat pump"_**
and
**_"Output temperature in °C at secondary side of the heat pump"_**

I am trying to link this model with my ground source heat pump model, but too many heat exchangers and temperatures, so sorry I get lost for these two temperatures.

Thank you~

**Comment by ttjaden** [comment]
"Input temperature in °C at primary side of the heat pump"

- For Brine/Water heat pumps this is the brine supply temperature
- For Air/Water heat pumps this is the outside air temperature

 "Output temperature in °C at secondary side of the heat pump"

- This is the supply temperature of the heat pump for domestic hot water or heating purpose

**Comment by Deepyman** [comment]
Thank you for your patience reply, I am now clear about it now.
